In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/hackerearth-defcon/train.csv
/kaggle/input/hackerearth-defcon/test.csv
/kaggle/input/hackerearth-defcon/sample_submission.csv


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error,confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [3]:
import pandas as pd
sample_submission = pd.read_csv("../input/hackerearth-defcon/sample_submission.csv")
X_test = pd.read_csv("../input/hackerearth-defcon/test.csv")
train = pd.read_csv("../input/hackerearth-defcon/train.csv")

In [4]:
train['DEFCON_Level'].value_counts()

2    4270
3    3910
4    1212
1     498
5     110
Name: DEFCON_Level, dtype: int64

### seprating features and target

In [5]:
parameter_train = X_test.columns
X = train[parameter_train]
Y = train['DEFCON_Level']
Y_test = sample_submission.DEFCON_Level

### splitting trian and test data using trian test split

In [6]:
#splitting into train and test set 
train_X,val_x,train_Y,val_y = train_test_split(X,Y,random_state =1)

### Random forest classifier

In [7]:
rfc_model = RandomForestClassifier(n_estimators = 500,random_state = 0)
rfc_model.fit(train_X,train_Y)
print(mean_absolute_error(rfc_model.predict(val_x),val_y))
print(confusion_matrix(rfc_model.predict(val_x),val_y))

0.4108
[[ 15  13   2   1   0]
 [ 75 771 287  22   1]
 [ 25 248 637 161   7]
 [  2  16  74 132  10]
 [  0   1   0   0   0]]


In [8]:
print("Random Forest model accuracy(in %):", metrics.accuracy_score(val_y,rfc_model.predict(val_x))*100)

Random Forest model accuracy(in %): 62.2


### KNN classifier model

In [9]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors = 30)
KNN.fit(train_X,train_Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=30, p=2,
                     weights='uniform')

In [10]:
print(mean_absolute_error(KNN.predict(val_x),val_y))
print(confusion_matrix(KNN.predict(val_x),val_y))
print("\n KNN model accuracy(in %):", metrics.accuracy_score(val_y,KNN.predict(val_x))*100)

0.5192
[[  0   0   0   0   0]
 [ 68 737 408  35   5]
 [ 46 299 543 238  11]
 [  3  13  49  43   2]
 [  0   0   0   0   0]]

 KNN model accuracy(in %): 52.92


Decission tree classifier

In [11]:
DTC = DecisionTreeClassifier(min_samples_split=100,random_state = 0)
DTC.fit(train_X,train_Y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=100,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [12]:
print(mean_absolute_error(DTC.predict(val_x),val_y))
print(confusion_matrix(DTC.predict(val_x),val_y))
print("\n Decision Tree model accuracy(in %):", metrics.accuracy_score(val_y,DTC.predict(val_x))*100)

0.406
[[ 11  11   1   0   0]
 [ 70 744 244  28   2]
 [ 33 274 678 140   4]
 [  3  20  77 148  12]
 [  0   0   0   0   0]]

 Decision Tree model accuracy(in %): 63.239999999999995


Predicting with the best model

In [13]:
preds = np.round(DTC.predict(X_test))
output = pd.DataFrame({"ID": X_test.ID,"DEFCON_Level": preds })
output.to_csv("hackerearth-defcon.csv",index = False)